image: "node:latest"
stages:
  - install
  - test
  - build
  - deploy
install:
  stage: install
  script:
    - echo "Starting to install node packages"
    - yarn install
  cache:
    key: $CI_JOB_NAME-$CI_COMMIT_REF_SLUG
    paths:
      - node_modules
  artifacts:
    paths:
      - node_modules
test:
  stage: test
  script:
    - echo "Starting to test"
    - yarn test
build:
  stage: build
  script:
    - echo "Starting to build"
    - yarn build
  artifacts:
    paths:
      - build
deploy:
  stage: deploy
  only:
    - master
  script:
    - echo "Starting to deploy to firebase"
    - yarn global add firebase-tools
    - firebase deploy --only hosting --token $FIREBASE_TOKEN
